### ISSUE TITLE
Add CI to run the tests

### ISSUE THREAD

**Issue by djmattyg007** [probablykasper/cpc#13]
It would be good to set up something like Github actions to run the tests, so that they're automatically validated when someone submits a PR.

**Comment by djmattyg007** [comment]
Similarly it would be good to run `rustfmt` and verify it with CI.

**Comment by probablykasper** [comment]
Yeah, a GitHub action would make sense. If I recall correctly, `rustfmt` screws up a lot of the formatting, so it would need to be disabled for certain files (or configured in some weird way?).

**Comment by djmattyg007** [comment]
It might be worth just accepting what `rustfmt` outputs if it's more consistent with the broader rust ecosystem.

**Comment by probablykasper** [comment]
Yeah, the main thing is that in `units.rs` it does this:
```diff
-  Nanosecond:         (Time, d128!(1)),
-  Microsecond:        (Time, d128!(1000)),
+  Nanosecond: (Time, d128!(1)),
+  Microsecond: (Time, d128!(1000)),
```

I'll look into if there's a way to prevent that because it makes it less readable and harder to edit.

The other thing is that I'd like all the matches in `lexer.rs` to be on single lines, but for that I can make the max line width an insane 200.

**Comment by probablykasper** [comment]
Couldn't find any option for it. Would work to use `ignore = [ "units.rs", "lookup.rs" ]`, but the `ignore` option isn't stable yet

**Comment by probablykasper** [comment]
Added test CI
