### ISSUE TITLE
Support non-US spelling of words

### ISSUE THREAD

**Issue by djmattyg007** [probablykasper/cpc#6]
These examples should work, but don't:

```
❯ ./cpc '24 kilometres per hour in metres per second'
Lexing error: Invalid string: kilometres

❯ ./cpc '24 kilometers per hour in metres per second'
Lexing error: Invalid string: metres
```

I'm guessing there are probably others that need fixing up; I didn't perform a comprehensive test of all supported units.

**Comment by probablykasper** [comment]
Neglected this at first because there are 50 keywords with the word meter, but would be good to add.

Might be some other spelling variations missing, but I don't think there's anything major. You can find all the keywords in [lexer.rs](https://github.com/probablykasper/cpc/blob/master/src/lexer.rs)
